// Inlines CSS + images into the HTML pages and writes them as JS modules.
// Generated files are committed so Cloudflare can deploy without a build step.
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const read = (p) => readFileSync(new URL(p, root));
const css = read('shared/theme.css').toString();

function inline(htmlPath, outPath, exportName) {
  let html = read(htmlPath).toString();
  html = html.replace(/<link rel="stylesheet" href="[^"]*theme\.css">/, () => `<style>${css}</style>`);
  html = html.replace(/(src|href|content)="((?:\.\.\/)+assets\/[^"]+)"/g, (_, attr, p) => {
    const file = read(p.replace(/^(\.\.\/)+/, ''));
    return `${attr}="data:image/png;base64,${file.toString('base64')}"`;
  });
  const banner = '// GENERATED by scripts/build.mjs from ' + htmlPath + ' - do not edit by hand.\n';
  writeFileSync(new URL(outPath, root), `${banner}export const ${exportName} = ${JSON.stringify(html)};\n`);
  console.log('built', outPath, (html.length / 1024).toFixed(1) + ' KB');
}

inline('wizard/ui/index.html', 'wizard/src/ui.generated.js', 'wizardHtml');
inline('panel/ui/app.html', 'panel/src/ui.generated.js', 'appHtml');
